import { Oswald, Permanent_Marker } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";


export const oswald = Oswald({ 
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-oswald",
});

export const sedgwick = Permanent_Marker({ 
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-sedgwick",
  weight: ['400']
});

export const metadata = {
  title: "Dianciré | Développeuse Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${oswald.variable} ${sedgwick.variable}`}>
      <body style={{backgroundImage: "url('/site-bg.jpg')"}}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
